default:
  variable: 10
models:
  Zero order: C[1]*t
  Zero order with lag time: C[1]*(t-C[2])
  First order: 100*(1-exp(-C[1]*t))
  First order with lag time: 100*(1-exp(-C[1]*t-C[2]))
  Second order: 100*(1-(C[1]/(1+C[1]*C[2]*t)))
  Second order with lag time: 100*(1-(C[1]/(1+C[1]*C[2]*(t-C[3]))))
  Third order: 100*(1-(1/(C[1]*t+1/(C[2])^2))^0.5)
  Third order with lag time: 100*(1-(1/(C[1]*(t-C[2])+1/(C[3])^2))^0.5)
  Michaelis-Menten: 100*t/(C[1]+t)
  Michaelis-Menten with lag time: 100*(t-C[1])/(C[2]+t-C[1])
  Weibull: 100*(1-exp(-((t^C[1]))/C[2]))
  Weibull with lag time: 100*(1-exp(-(((t-C[1])^C[2]))/C[3]))
  Double Weibull: 100*(C[1]*(1-exp(-((t^C[2]))/C[3]))+C[4]*(1-exp(-((t^C[5]))/C[6])))
  Double Weibull with lag time: 100*(C[1]*(1-exp(-(((t-C[2])^C[3]))/C[4]))+C[5]*(1-exp(-(((t-C[2])^C[6]))/C[7])))
  Higuchi: C[1]*t^0.5
  Higuchi with lag time: C[1]*(t-C[2])^0.5
  Hixson-Crowley: 100*(1-(1-C[1]*t)^3)
  Hixson-Crowley with lag time: 100*(1-(1-C[1]*(t-C[2]))^3)
  Korsmeyer-Peppas: C[1]*t^C[2]
  Korsmeyer-Peppas with lag time: C[1]*(t-C[2])^C[3]
  Hill: 100*t^C[1]/C[2]^C[1]+t^C[1]
  Hill with lag time: 100*(t-C[1])^C[2]/C[3]^C[2]+(t-C[1])^C[2]
  Hopfenberg: 100*(1-(1-C[1]*t)^C[2])
  Hopfenberg with lag time: 100*(1-(1-C[1]*(t-C[2]))^C[3])
  Peppas-Sahlin: C[1]*t^C[2]+C[3]*t^(2*C[2])
  Peppas-Sahlin with lag time: C[1]*(t-C[2])^C[3]+C[4]*(t-C[2])^(2*C[3])
  Quadratic: 100*(C[1]*t^2+C[2]*t)
  Quadratic with lag time: 100*(C[1]*(t-C[2])^2+C[3]*(t-C[2]))
  Logistic: C[1]/1+exp(-C[2]*(t-C[3]))
  Logistic with lag time: C[1]/1+exp(-C[2]*((t-C[3])-C[4]))
  Gompertz: 100*(exp(-C[1]*(exp(-C[2]*log10(t)))))
  Gompertz with lag time: 100*(exp(-C[1]*(exp(-C[2]*log10(t-(C[3]))))))
  Makoid-Banakar: C[1]*t^C[2]*exp(-C[3]*t)
  Makoid-Banakar with lag time: C[1]*(t-C[2])^C[3]*exp(-C[4]*(t-C[2]))
  Baker-Lonsdale: 100*(3/2*(1-(1-C[1])^(2/3))-C[2]*t)
  Baker-Lonsdale with lag time: 100*(3/2*(1-(1-C[1])^(2/3))-C[2]*(t-C[3]))
selected_modelsx:
  selected_models:
  - 1
  - 3
  - 5
  - 7
optim_method:
  SANN: no
  nloptr: yes
  NelderMead: no
  genSA: no
  rgenoud: no
running_params:
  maxit_BFGS: 5000
  maxit_SANN: 10000
  maxit_nloptr: 10000
  max_iter_gensa: 1500
  max_iter_rgenoud: 500
  maxit_NM: 500000
  optim_rel_tol: 1.0e-20
  opti_trace: yes
data:
  headers: yes
